config/routes.rb
Rails.application.routes.draw do
#   devise_for :customers, controllers: {
#   registrations: "public/registrations",
#   sessions: 'public/sessions'
# }
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#   devise_for :admins, controllers: {
#   sessions: "admin/sessions"
# }
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 root to: 'public/homes#top'
    # アプリに対して1つ↑
    # 条件分岐
    # Bookers<% if user_signed_in? %>

  namespace :public do
    get "home/about"=>"homes#about", as: "about"

    # URLの頭にしたい部分
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show', as: "customer"
    get 'customers/information/edit' => 'customers#edit', as: "customers_edit"
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    post 'orders/confirm', to: 'orders#confirm'
    get "orders/complete" => "orders#complete", as: "complete"
    resources :cart_items, only: [:index, :update, :create, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :update, :show, :edit]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  # namespace :admin do
  #   get 'orders/show'
  # end
  # namespace :admin do
  #   get 'customers/index'
  #   get 'customers/show'
  #   get 'customers/edit'
  # end
  # namespace :admin do
  #   get 'genres/index'
  #   get 'genres/edit'
  # end
  # namespace :admin do
  #   get 'items/index'
  #   get 'items/new'
  #   get 'items/show'
  #   get 'items/edit'
  # end
  # namespace :admin do
  #   get 'homes/top'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/edit'
  #   get 'customers/unsubscribe'
  # end
  # namespace :public do
  #   get 'addresses/index'
  #   get 'addresses/edit'
  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/complete'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def new
  @item = current_customer.items.build
  @genres = Genre.all
  @genre = Genre.new
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path(@genre)
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render "edit"
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
      <tr>
        
        <td><%= link_to customer_items_path(genre.id) do %>
        <% ganre.name %><% end %></td>
      　<td>
       
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/edit.html.erb
<div class="container">
  <h5>ジャンル編集</h5>
　　<%= form_with model: @genre, url: admin_genre_path do |f| %>
      <div class="form-group">
        <%= f.label :"ジャンル名　" %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <input type="submit" name="commit" value="Update Genre" class="btn btn-outline-success" data-disable-with="Update Genre">
      </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h5>ジャンル一覧・追加</h5>
  <%= form_with model: @genre, url: admin_genres_path do |f| %>
  <table class='table table-bordered'>
    <thead>
      <div class="form-group">
          <%= f.label :"ジャンル名　" %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-outline-success' %>
        </div>
    </thead>
  </table>
  <% end %>
  <div class="row">
    <div class="col-md-4">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th></th>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td></td>
              <td><%= genre.name %></td>
              <td>
                <%= link_to '編集', edit_admin_genre_path(genre), class: "btn btn-sm btn-outline-success" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>