config/routes.rb
Rails.application.routes.draw do
#   devise_for :customers, controllers: {
#   registrations: "public/registrations",
#   sessions: 'public/sessions'
# }
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#   devise_for :admins, controllers: {
#   sessions: "admin/sessions"
# }
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 root to: 'public/homes#top'
    # アプリに対して1つ↑
    # 条件分岐
    # Bookers<% if user_signed_in? %>

  namespace :public do
    get "home/about"=>"homes#about", as: "about"

    # URLの頭にしたい部分
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show', as: "customer"
    get 'customers/information/edit' => 'customers#edit', as: "customers_edit"
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    post 'orders/confirm', to: 'orders#confirm'
    get "orders/complete" => "orders#complete", as: "complete"
    resources :cart_items, only: [:index, :update, :create, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :update, :show, :edit]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  # namespace :admin do
  #   get 'orders/show'
  # end
  # namespace :admin do
  #   get 'customers/index'
  #   get 'customers/show'
  #   get 'customers/edit'
  # end
  # namespace :admin do
  #   get 'genres/index'
  #   get 'genres/edit'
  # end
  # namespace :admin do
  #   get 'items/index'
  #   get 'items/new'
  #   get 'items/show'
  #   get 'items/edit'
  # end
  # namespace :admin do
  #   get 'homes/top'
  # end
  # namespace :public do
  #   get 'customers/show'
  #   get 'customers/edit'
  #   get 'customers/unsubscribe'
  # end
  # namespace :public do
  #   get 'addresses/index'
  #   get 'addresses/edit'
  # end
  # namespace :public do
  #   get 'orders/new'
  #   get 'orders/complete'
  #   get 'orders/index'
  #   get 'orders/show'
  # end
  # namespace :public do
  #   get 'cart_items/index'
  # end
  # namespace :public do
  #   get 'items/index'
  #   get 'items/show'
  # end
  # namespace :public do
  #   get 'homes/top'
  #   get 'homes/about'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<header>			
    <nav class="navbar navbar-expand-lg navbar-info bg-info">			
        <div class="container">			
        <span class="navbar-toggler-icon"></span>			
                <ul class="navbar-nav ml-auto">	
                <p>©nagano</p>
                </ul>			
        </div>			
    </nav>			
</header>			

app/views/layouts/_header.html.erb
<header>			
    <nav class="navbar navbar-expand-lg navbar-info bg-info">			
        <div class="container">			
        <a class="navbar-brand" href="/"><span>Nagano Cake</span></a>			
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">			
        <span class="navbar-toggler-icon"></span>			
        </button>			
            <div class="collapse navbar-collapse" id="navbarNavDropdown">			
                <ul class="navbar-nav ml-auto">			
                    <% if customer_signed_in? %>			
                        <li>			
                         <%= link_to public_customer_path(current_customer),class: 'nav-link text-light' do %>			
                         マイページ			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%=  link_to public_items_path,class: 'nav-link text-light' do %>			
                         商品一覧			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%=  link_to public_cart_items_path ,class: 'nav-link text-light' do %>			
                         カート			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>			
                         logout			
                         <% end %>			
                        </li>			
                        			
                    <% else %>			
                        <li>			
                         <%= link_to public_about_path,class: 'nav-link text-light' do %>			
                         About			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%= link_to public_items_path,class: 'nav-link text-light' do %>			
                         商品一覧			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>			
                         新規登録			
                         <% end %>			
                        </li>
                        
                        <li>			
                         <%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>			
                         login			
                         <% end %>			
                        </li>			
                    <% end %>			
                </ul>			
            </div>			
        </div>			
    </nav>			
</header>			

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="d-flex flex-column vh-100" style="background-color: #fffaf0;">
      <header class="shadow-sm mb-5" >
        <nav class="navbar expand-lg navbar-dark" style="background-color: #BBBBBB;">

          <div class="container">
            <% if admin_signed_in? %>
              <%= link_to admin_root_path do %>
                <%= image_tag "logo.jpg", size: "100x100" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </ul>
            <% elsif customer_signed_in? %>
              <%= link_to root_path do %>
                <%= image_tag "logo.jpg", size: "100x100" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "マイページ", public_customer_path(current_customer.id), class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "カート", public_cart_items_path(current_customer.id), class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </ul>
            <% else %>
              <%= link_to root_path do %>
                <%= image_tag "logo.jpg", size: "100x100" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "About", public_about_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %></li>
              </ul>
            <% end %>
          </div>
        </nav>
      </header>
        <main class="body-by">
          <%= yield %>

        </main>
      <footer class="text-dark pt-5 pb-3">
        <div class='container'>
    	    <div class='row'>
      	    <div class='mx-auto'>
                <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-lg"></i></a>
                <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-lg"></i></a>
                <a href="#" class="mx-1 text-dark"><i class="fab fa-facebook-square"></i></a>
                <a href="#" class="mx-5 text-dark"><i class="far fa-envelope fa-lg"></i></a>
                <p class="text-center">© REVENGERS </p>
              </div>
           </div>
         </div>
      </footer>
    </body>
</html>